"""Mechanically translate the shared CUDA move algorithm to OpenCL 1.2."""
from __future__ import annotations
import argparse
import hashlib
from pathlib import Path
import re


def to_opencl(cuda_source: str) -> str:
    """Translate only execution/address-space syntax, preserving algorithm text."""
    result = cuda_source.replace('__device__ __forceinline__', 'inline')
    result = result.replace('extern "C" __global__', '__kernel')
    result = result.replace('(int)(blockIdx.x * blockDim.x + threadIdx.x)', '(int)get_global_id(0)')
    result = result.replace('expf(', 'exp(')
    pattern = r'\b((?:const\s+)?(?:unsigned long long|unsigned char|unsigned int|short|int|float))\s*\*(\w+)'
    def pointer(match):
        qualifier = '__private' if match[2] == 'state' else '__global'
        return f'{qualifier} {match[1]} *{match[2]}'
    result = re.sub(pattern, pointer, result)
    result = result.replace('unsigned long long', 'ulong')
    if 'unsigned int &state' in result:
        raise ValueError('CUDA RNG must use the shared pointer convention')
    if any(token in result for token in ('__device__', '__forceinline__', 'blockIdx.', 'threadIdx.', 'blockDim.')):
        raise ValueError('Untranslated CUDA construct')
    digest = hashlib.sha256(cuda_source.encode('utf-8')).hexdigest()
    return '// Generated by kernel_port.py; source SHA256: ' + digest + '\n' + result


def verified_opencl_source(directory: Path) -> str:
    expected = to_opencl((directory / 'kernels.cu').read_text(encoding='utf-8'))
    actual = (directory / 'kernels.cl').read_text(encoding='utf-8')
    if actual != expected:
        raise RuntimeError('OpenCL kernel differs from the shared CUDA algorithm; regenerate it with python kernel_port.py')
    return actual


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    directory = Path(__file__).resolve().parent
    if args.check:
        verified_opencl_source(directory)
        print('OpenCL kernel exactly matches the mechanical CUDA translation')
    else:
        source = (directory / 'kernels.cu').read_text(encoding='utf-8')
        (directory / 'kernels.cl').write_text(to_opencl(source), encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
